=== SyedTabishAzam/GUIPlugin/sm_db/default/Profile_Category.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Profile_Category (Database_Name, Timestamp, Profile_ID, Profile_Instance*, Additional_Folder*) >
<!ATTLIST Profile_Category Name CDATA #REQUIRED>
<!ELEMENT Database_Name (#PCDATA)>
<!ELEMENT Timestamp (#PCDATA)>
<!ELEMENT Profile_ID (#PCDATA)>
<!ELEMENT Profile_Instance (#PCDATA)>
<!ATTLIST Profile_Instance 
    Name CDATA #REQUIRED
	Folder_Name CDATA #IMPLIED
	>
<!ELEMENT Additional_Folder (#PCDATA)>

=== SyedTabishAzam/GUIPlugin/sm_db/default/sensor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Profile_Category SYSTEM "Profile_Category.dtd">
<Profile_Category Name="sensor">
  <Database_Name>default</Database_Name>
  <Timestamp>1481657865</Timestamp>
  <Profile_ID>17</Profile_ID>
  <Profile_Instance Folder_Name="\ESM" Name="generic ESM">sensor/generic ESM.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Laser" Name="Nd-YAG Seeker">sensor/Nd-YAG Seeker.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Missile Seeker" Name="AGM-65B Seeker">sensor/AGM-65B Seeker.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Missile Seeker" Name="AGM-65D Seeker">sensor/AGM-65D Seeker.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Missile Seeker" Name="AIM-120 Seeker">sensor/AIM-120 Seeker.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Missile Seeker" Name="AIM-7M Seeker">sensor/AIM-7M Seeker.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Missile Seeker" Name="AIM-9 Seeker">sensor/AIM-9 Seeker.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Missile Seeker" Name="Astra Seeker">sensor/Astra Seeker.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Missile Seeker" Name="R-77 Seeker">sensor/R-77 Seeker.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Missile Seeker" Name="RIM-7 Seeker">sensor/RIM-7 Seeker.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Missile Seeker" Name="Standard Infrared Seeker">sensor/Standard Infrared Seeker.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Missile Seeker" Name="Standard Radar Seeker">sensor/Standard Radar Seeker.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Airborne Radar" Name="AI.24 (Foxhunter)">sensor/AI.24 (Foxhunter).sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Airborne Radar" Name="AN/AAR-60 MILDS">sensor/AN/AAR-60 MILDS.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Airborne Radar" Name="AN/APG-68(V)">sensor/AN/APG-68(V).sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Airborne Radar" Name="AN/APG-70">sensor/AN/APG-70.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Airborne Radar" Name="AN/APG-73">sensor/AN/APG-73.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Airborne Radar" Name="AN/APG-77">sensor/AN/APG-77.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Airborne Radar" Name="AN/APG-78 Longbow">sensor/AN/APG-78 Longbow.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Airborne Radar" Name="AN/APQ-164">sensor/AN/APQ-164.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Airborne Radar" Name="AN/APQ-180">sensor/AN/APQ-180.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Airborne Radar" Name="AN/APS-124">sensor/AN/APS-124.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Airborne Radar" Name="AN/APS-133(V)">sensor/AN/APS-133(V).sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Airborne Radar" Name="AN/APY-1">sensor/AN/APY-1.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Airborne Radar" Name="AN/APY-3">sensor/AN/APY-3.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Airborne Radar" Name="ECR 90 Captor">sensor/ECR 90 Captor.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Airborne Radar" Name="ERDE/HAL X-band">sensor/ERDE/HAL X-band.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Airborne Radar" Name="ESSD L-(MESA)">sensor/ESSD L-(MESA).sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Airborne Radar" Name="NIIP N001 Mech">sensor/NIIP N001 Mech.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Airborne Radar" Name="RDY-2">sensor/RDY-2.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Airborne Radar" Name="Sapfir-23ML">sensor/Sapfir-23ML.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Airborne Radar" Name="Zhuk-M">sensor/Zhuk-M.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Site Radar" Name="Fan Song Guidance">sensor/Fan Song Guidance.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar\Site Radar" Name="P-12 Spoon Rest">sensor/P-12 Spoon Rest.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Radar" Name="generic radar 50km">sensor/generic radar 50km.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Sonar\Active" Name="generic sonar 15km">sensor/generic sonar 15km.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Sonar\Active" Name="generic sonar 25km">sensor/generic sonar 25km.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Visual" Name="Crew eyes 180">sensor/Crew eyes 180.sensor</Profile_Instance>
  <Profile_Instance Folder_Name="\Visual" Name="Crew eyes 360">sensor/Crew eyes 360.sensor</Profile_Instance>
</Profile_Category>

=== SyedTabishAzam/GUIPlugin/sm_db/default/me_mission.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Profile_Category SYSTEM "Profile_Category.dtd">
<Profile_Category Name="me_mission">
  <Database_Name>default</Database_Name>
  <Timestamp>1535347389</Timestamp>
  <Profile_ID>11</Profile_ID>
  <Profile_Instance Folder_Name="\Scenario Specific\Airport Sample" Name="Air defense">me_mission/Air defense.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Airport Sample" Name="Air to Air">me_mission/Air to Air.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Airport Sample" Name="Air to Ground">me_mission/Air to Ground.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Airport Sample" Name="EscortMission 1">me_mission/EscortMission 1.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Airport Sample" Name="EscortMission 2">me_mission/EscortMission 2.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Airport Sample" Name="LeopardMission">me_mission/LeopardMission.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Airport Sample" Name="MasterMission">me_mission/MasterMission.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Airport Sample" Name="MigMission">me_mission/MigMission.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Airport Sample" Name="RescuedSoldierMission">me_mission/RescuedSoldierMission.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Airport Sample" Name="SoldierMission">me_mission/SoldierMission.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Bombing Sample" Name="Blue Fighter">me_mission/Blue Fighter.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Bombing Sample" Name="Blue Soldier">me_mission/Blue Soldier.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Bombing Sample" Name="Red Tank">me_mission/Red Tank.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\CAP Air Sample" Name="CAP Awacs">me_mission/CAP Awacs.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\CAP Air Sample" Name="CAP Leader">me_mission/CAP Leader.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\CAP Air Sample" Name="CAP Wingman">me_mission/CAP Wingman.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\DI-Guy Sample" Name="DI-Guy Demo Insurgent">me_mission/DI-Guy Demo Insurgent.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\DI-Guy Sample" Name="DI-Guy Demo Sergeant">me_mission/DI-Guy Demo Sergeant.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\DI-Guy Sample" Name="DI-Guy Demo Soldier">me_mission/DI-Guy Demo Soldier.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Ground Sample" Name="Ground Demo Escort Helo">me_mission/Ground Demo Escort Helo.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Ground Sample" Name="Ground Demo Tank">me_mission/Ground Demo Tank.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Ground_Air_Defense" Name="Hind_defensse">me_mission/Hind_defensse.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Ground_Air_Defense" Name="ManPAD Observer">me_mission/ManPAD Observer.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Ground_Air_Defense" Name="ManPAD_Gunner">me_mission/ManPAD_Gunner.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Ground_Air_Defense" Name="ManPad Commander">me_mission/ManPad Commander.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Ground_Air_Defense" Name="Man_Unit">me_mission/Man_Unit.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Surface Sample" Name="Surf Demo Arleigh Burke">me_mission/Surf Demo Arleigh Burke.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Surface Sample" Name="Surf Demo Submarine">me_mission/Surf Demo Submarine.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\UAS LGB Sample" Name="CNC">me_mission/CNC.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\UAS LGB Sample" Name="ForwardObserver">me_mission/ForwardObserver.me_mission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\UAS LGB Sample" Name="MQ9">me_mission/MQ9.me_mission</Profile_Instance>
  <Profile_Instance Name="Bomber">me_mission/Bomber.me_mission</Profile_Instance>
  <Profile_Instance Name="Civilian Wander">me_mission/Civilian Wander.me_mission</Profile_Instance>
  <Profile_Instance Name="EmbarkedSoldier">me_mission/EmbarkedSoldier.me_mission</Profile_Instance>
  <Profile_Instance Name="Enemy1">me_mission/Enemy1.me_mission</Profile_Instance>
  <Profile_Instance Name="Enemy2">me_mission/Enemy2.me_mission</Profile_Instance>
  <Profile_Instance Name="Friend1">me_mission/Friend1.me_mission</Profile_Instance>
  <Profile_Instance Name="Friend2">me_mission/Friend2.me_mission</Profile_Instance>
  <Profile_Instance Name="KillEnemy">me_mission/KillEnemy.me_mission</Profile_Instance>
  <Profile_Instance Name="QRFTask">me_mission/QRFTask.me_mission</Profile_Instance>
  <Profile_Instance Name="Traffic">me_mission/Traffic.me_mission</Profile_Instance>
</Profile_Category>

=== SyedTabishAzam/GUIPlugin/sm_db/default/supply.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Profile_Category SYSTEM "Profile_Category.dtd">
<Profile_Category Name="supply">
  <Database_Name>default</Database_Name>
  <Timestamp>1481657865</Timestamp>
  <Profile_ID>19</Profile_ID>
  <Profile_Instance Folder_Name="\Decon" Name="Decon - Agent STB">supply/Decon - Agent STB.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Decon" Name="Decon - Ferric Chloride">supply/Decon - Ferric Chloride.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Decon" Name="Decon - Other">supply/Decon - Other.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Equipment" Name="Equipment - Mine Plow">supply/Equipment - Mine Plow.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Equipment" Name="Equipment - Mine Rollers">supply/Equipment - Mine Rollers.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Equipment" Name="Equipment - Other">supply/Equipment - Other.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Food" Name="Food - Bread">supply/Food - Bread.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Food" Name="Food - H-Daily Ration">supply/Food - H-Daily Ration.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Food" Name="Food - LRP Ration">supply/Food - LRP Ration.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Food" Name="Food - MRE">supply/Food - MRE.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Food" Name="Food - Meal Cold Weather">supply/Food - Meal Cold Weather.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Food" Name="Food - Water Clear">supply/Food - Water Clear.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Food" Name="Food - Water Dist - Sparkling">supply/Food - Water Dist - Sparkling.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Food" Name="Food- MRE Vegitarian">supply/Food- MRE Vegitarian.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Fuel" Name="Fuel - Diesel">supply/Fuel - Diesel.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Fuel" Name="Fuel - Fog Oil">supply/Fuel - Fog Oil.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Fuel" Name="Fuel - Fuel Oil">supply/Fuel - Fuel Oil.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Fuel" Name="Fuel - Gasoline">supply/Fuel - Gasoline.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Fuel" Name="Fuel - JP-4">supply/Fuel - JP-4.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Fuel" Name="Fuel - JP-8">supply/Fuel - JP-8.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Fuel" Name="Fuel - Multi-Spectral Fog Oil">supply/Fuel - Multi-Spectral Fog Oil.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Fuel" Name="Fuel - Other">supply/Fuel - Other.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Lubricants" Name="Lubricants">supply/Lubricants.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Oils" Name="Oils">supply/Oils.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Pallets" Name="Pallets of Fuel (JP8)">supply/Pallets of Fuel (JP8).supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Pallets" Name="Pallets with Ammunition">supply/Pallets with Ammunition.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Pallets" Name="Pallets with Water">supply/Pallets with Water.supply</Profile_Instance>
  <Profile_Instance Folder_Name="\Spare Parts" Name="Spare Parts">supply/Spare Parts.supply</Profile_Instance>
</Profile_Category>

=== SyedTabishAzam/GUIPlugin/sm_db/default/art_part.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Profile_Category SYSTEM "Profile_Category.dtd">
<Profile_Category Name="art_part">
  <Database_Name>default</Database_Name>
  <Timestamp>1481657862</Timestamp>
  <Profile_ID>3</Profile_ID>
  <Profile_Instance Name="Turret IFV">art_part/Turret IFV.art_part</Profile_Instance>
  <Profile_Instance Name="Turret MBT">art_part/Turret MBT.art_part</Profile_Instance>
  <Profile_Instance Name="Turret MG">art_part/Turret MG.art_part</Profile_Instance>
  <Profile_Instance Name="Turret TOW">art_part/Turret TOW.art_part</Profile_Instance>
</Profile_Category>

=== SyedTabishAzam/GUIPlugin/sm_db/default/designator.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Profile_Category SYSTEM "Profile_Category.dtd">
<Profile_Category Name="designator">
  <Database_Name>default</Database_Name>
  <Timestamp>1481657862</Timestamp>
  <Profile_ID>7</Profile_ID>
  <Profile_Instance Folder_Name="\Manportable" Name="AN/PAQ-1">designator/AN/PAQ-1.designator</Profile_Instance>
  <Profile_Instance Folder_Name="\Manportable" Name="AN/TVQ-2">designator/AN/TVQ-2.designator</Profile_Instance>
  <Profile_Instance Name="AN/AWS-1(V)1">designator/AN/AWS-1(V)1.designator</Profile_Instance>
  <Profile_Instance Name="ASQ-228">designator/ASQ-228.designator</Profile_Instance>
</Profile_Category>

=== SyedTabishAzam/GUIPlugin/sm_db/default/me_submission.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Profile_Category SYSTEM "Profile_Category.dtd">
<Profile_Category Name="me_submission">
  <Database_Name>default</Database_Name>
  <Timestamp>1535347040</Timestamp>
  <Profile_ID>12</Profile_ID>
  <Profile_Instance Folder_Name="\Scenario Specific\Airport Sample" Name="AirTo Air sub-mission">me_submission/AirTo Air sub-mission.me_submission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Airport Sample" Name="AirTo Ground sub-mission">me_submission/AirTo Ground sub-mission.me_submission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Airport Sample" Name="LeopardEmbarkSubmission">me_submission/LeopardEmbarkSubmission.me_submission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Bombing Sample" Name="Bomb Delivery">me_submission/Bomb Delivery.me_submission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\CAP Air Sample" Name="CAP Leader Attack">me_submission/CAP Leader Attack.me_submission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\DI-Guy Sample" Name="FindNewHostile">me_submission/FindNewHostile.me_submission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\DI-Guy Sample" Name="GetInPosition">me_submission/GetInPosition.me_submission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\DI-Guy Sample" Name="GotoObjectivePoint">me_submission/GotoObjectivePoint.me_submission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\DI-Guy Sample" Name="GotoRallyPoint">me_submission/GotoRallyPoint.me_submission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\DI-Guy Sample" Name="TakeOutHostile">me_submission/TakeOutHostile.me_submission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Surface Sample" Name="Arleigh Burke Attack Ground">me_submission/Arleigh Burke Attack Ground.me_submission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\Surface Sample" Name="Arleigh Burke Drop Decoy">me_submission/Arleigh Burke Drop Decoy.me_submission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\UAS LGB Sample" Name="AirBombRun">me_submission/AirBombRun.me_submission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\UAS LGB Sample" Name="AirNavigateTarget">me_submission/AirNavigateTarget.me_submission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\UAS LGB Sample" Name="FOBombRun">me_submission/FOBombRun.me_submission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\UAS LGB Sample" Name="FOMonitorStrike">me_submission/FOMonitorStrike.me_submission</Profile_Instance>
  <Profile_Instance Folder_Name="\Scenario Specific\UAS LGB Sample" Name="RecheckTarget">me_submission/RecheckTarget.me_submission</Profile_Instance>
</Profile_Category>

=== SyedTabishAzam/GUIPlugin/sm_db/default/countermeasure.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Profile_Category SYSTEM "Profile_Category.dtd">
<Profile_Category Name="countermeasure">
  <Database_Name>default</Database_Name>
  <Timestamp>1481657862</Timestamp>
  <Profile_ID>6</Profile_ID>
  <Profile_Instance Name="Acoustic Decoy">countermeasure/Acoustic Decoy.countermeasure</Profile_Instance>
  <Profile_Instance Name="Chaff">countermeasure/Chaff.countermeasure</Profile_Instance>
  <Profile_Instance Name="Flare">countermeasure/Flare.countermeasure</Profile_Instance>
  <Profile_Instance Name="Infrared Jammer">countermeasure/Infrared Jammer.countermeasure</Profile_Instance>
  <Profile_Instance Name="Radar Jammer">countermeasure/Radar Jammer.countermeasure</Profile_Instance>
  <Profile_Instance Name="Smoke">countermeasure/Smoke.countermeasure</Profile_Instance>
</Profile_Category>
