=== SyedTabishAzam/GUIPlugin/sm_db/default/weapon/Profile.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Profile_Instance (Database_Name, Stage_Version, Timestamp, Profile_ID, Instance_ID, Field*)>
<!ATTLIST Profile_Instance
	Name CDATA #REQUIRED
>
<!ELEMENT Database_Name (#PCDATA)>
<!ELEMENT Stage_Version (#PCDATA)>
<!ELEMENT Timestamp (#PCDATA)>
<!ELEMENT Profile_ID (#PCDATA)>
<!ELEMENT Instance_ID (#PCDATA)>
<!ELEMENT Field (Name,FieldID, Datablock*, Gfx*, LatLon*, DBList*, Curve*, Value*, DBChoice*)>
<!ATTLIST Field
	Type CDATA #REQUIRED
	Type_Name CDATA #IMPLIED
>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT FieldID (#PCDATA)>
<!ELEMENT Gfx (Marker*, Point)>
<!ATTLIST  Gfx
	Attrib_File CDATA #REQUIRED
	Attrib_Sub_Dir CDATA #REQUIRED
	Num_Points CDATA #REQUIRED
	Type CDATA #REQUIRED
>
<!ELEMENT Marker (#PCDATA)>

<!ELEMENT LatLon (Lat, Lon)>
<!ELEMENT Lat (#PCDATA)>
<!ELEMENT Lon (#PCDATA)>

<!ELEMENT DBList (DBList_Instance*,Datablock_Instance*,Additional_Folder*)>
<!ELEMENT DBList_Instance (Field*)>
<!ATTLIST DBList_Instance	
Name CDATA #REQUIRED
>

<!ELEMENT Datablock_Instance (#PCDATA)>
<!ATTLIST Datablock_Instance
	Name CDATA #REQUIRED
	Folder_Name CDATA #IMPLIED
>

<!ELEMENT Additional_Folder (#PCDATA)>

<!ELEMENT Curve (Z*)>
<!ELEMENT Z (Point*)>
<!ATTLIST Z
	Value CDATA #IMPLIED
>
<!ELEMENT Point (#PCDATA)>
<!ATTLIST Point
	X CDATA #IMPLIED
	Y CDATA #IMPLIED
	Alt CDATA #IMPLIED
	Lat CDATA #IMPLIED
	Lon CDATA #IMPLIED
>

<!ELEMENT Value (#PCDATA)>

<!ELEMENT DBChoice (Choice, Datablock)>
<!ELEMENT Choice (#PCDATA)>
<!ELEMENT Datablock (Field*)>

=== SyedTabishAzam/GUIPlugin/sm_db/default/me_mission/KillEnemy - Copy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Profile_Instance SYSTEM "Profile.dtd">
<Profile_Instance Name="KillEnemy">
  <Database_Name>default</Database_Name>
  <Stage_Version>16.0.0</Stage_Version>
  <Timestamp>1533720787</Timestamp>
  <Profile_ID>11</Profile_ID>
  <Instance_ID>41</Instance_ID>
  <Field Type="11" Type_Name="Datablock List">
    <Name>task_group</Name>
    <FieldID>2</FieldID>
    <DBList>
      <DBList_Instance Name="Init">
        <Field Type="3" Type_Name="String">
          <Name>name</Name>
          <FieldID>1</FieldID>
          <Value>Init</Value>
        </Field>
        <Field Type="9" Type_Name="Integer Choice">
          <Name>type</Name>
          <FieldID>2</FieldID>
          <Value>100000001</Value>
        </Field>
        <Field Type="10" Type_Name="Datablock Reference">
          <Name>event_task</Name>
          <FieldID>3</FieldID>
          <Datablock>
            <Field Type="10" Type_Name="Datablock Reference">
              <Name>event</Name>
              <FieldID>1</FieldID>
              <Datablock>
                <Field Type="9" Type_Name="Integer Choice">
                  <Name>type</Name>
                  <FieldID>1</FieldID>
                  <Value>100000004</Value>
                </Field>
                <Field Type="3" Type_Name="String">
                  <Name>value</Name>
                  <FieldID>2</FieldID>
                  <Value/>
                </Field>
                <Field Type="9" Type_Name="Integer Choice">
                  <Name>send_mode</Name>
                  <FieldID>3</FieldID>
                  <Value>100000001</Value>
                </Field>
                <Field Type="9" Type_Name="Integer Choice">
                  <Name>send_medium</Name>
                  <FieldID>4</FieldID>
                  <Value>100000001</Value>
                </Field>
                <Field Type="11" Type_Name="Datablock List">
                  <Name>to</Name>
                  <FieldID>5</FieldID>
                  <DBList/>
                </Field>
                <Field Type="3" Type_Name="String">
                  <Name>from</Name>
                  <FieldID>6</FieldID>
                  <Value/>
                </Field>
                <Field Type="9" Type_Name="Integer Choice">
                  <Name>end_reason</Name>
                  <FieldID>7</FieldID>
                  <Value>100000001</Value>
                </Field>
                <Field Type="3" Type_Name="String">
                  <Name>reason</Name>
                  <FieldID>8</FieldID>
                  <Value/>
                </Field>
                <Field Type="13">
                  <Name>sim_ptr</Name>
                  <FieldID>9</FieldID>
                </Field>
              </Datablock>
            </Field>
            <Field Type="11" Type_Name="Datablock List">
              <Name>actions</Name>
              <FieldID>2</FieldID>
              <DBList>
                <DBList_Instance Name="Track Cycle On">
                  <Field Type="3" Type_Name="String">
                    <Name>name</Name>
                    <FieldID>1</FieldID>
                    <Value>Track Cycle On</Value>
                  </Field>
                  <Field Type="12" Type_Name="Datablock Choice">
                    <Name>type_obj</Name>
                    <FieldID>2</FieldID>
                    <DBChoice>
                      <Choice>100000002</Choice>
                      <Datablock>
                        <Field Type="3" Type_Name="String">
                          <Name>proc_name</Name>
                          <FieldID>1</FieldID>
                          <Value>Track Cycle On</Value>
                        </Field>
                        <Field Type="3" Type_Name="String">
                          <Name>reason</Name>
                          <FieldID>2</FieldID>
                          <Value/>
                        </Field>
                        <Field Type="11" Type_Name="Datablock List">
                          <Name>parameters</Name>
                          <FieldID>3</FieldID>
                          <DBList>
                            <DBList_Instance Name="Detected">
                              <Field Type="3" Type_Name="String">
                                <Name>name</Name>
                                <FieldID>1</FieldID>
                                <Value>Detected</Value>
                              </Field>
                              <Field Type="9" Type_Name="Integer Choice">
                                <Name>source</Name>
                                <FieldID>2</FieldID>
                                <Value>100000001</Value>
                              </Field>
                              <Field Type="3" Type_Name="String">
                                <Name>value</Name>
                                <FieldID>3</FieldID>
                                <Value>yes</Value>
                              </Field>
                            </DBList_Instance>
                            <DBList_Instance Name="Class">
                              <Field Type="3" Type_Name="String">
                                <Name>name</Name>
                                <FieldID>1</FieldID>
                                <Value>Class</Value>
                              </Field>
                              <Field Type="9" Type_Name="Integer Choice">
                                <Name>source</Name>
                                <FieldID>2</FieldID>
                                <Value>100000001</Value>
                              </Field>
                              <Field Type="3" Type_Name="String">
                                <Name>value</Name>
                                <FieldID>3</FieldID>
                                <Value>all</Value>
                              </Field>
                            </DBList_Instance>
                          </DBList>
                        </Field>
                        <Field Type="11" Type_Name="Datablock List">
                          <Name>long_params</Name>
                          <FieldID>4</FieldID>
                          <DBList/>
                        </Field>
                        <Field Type="13">
                          <Name>procedure_info</Name>
                          <FieldID>5</FieldID>
                        </Field>
                      </Datablock>
                    </DBChoice>
                  </Field>
                  <Field Type="13">
                    <Name>sim_ptr</Name>
                    <FieldID>3</FieldID>
                  </Field>
                </DBList_Instance>
                <DBList_Instance Name="Create Variable">
                  <Field Type="3" Type_Name="String">
                    <Name>name</Name>
                    <FieldID>1</FieldID>
                    <Value>Create Variable</Value>
                  </Field>
                  <Field Type="12" Type_Name="Datablock Choice">
                    <Name>type_obj</Name>
                    <FieldID>2</FieldID>
                    <DBChoice>
                      <Choice>100000002</Choice>
                      <Datablock>
                        <Field Type="3" Type_Name="String">
                          <Name>proc_name</Name>
                          <FieldID>1</FieldID>
                          <Value>loc_var_create</Value>
                        </Field>
                        <Field Type="3" Type_Name="String">
                          <Name>reason</Name>
                          <FieldID>2</FieldID>
                          <Value/>
                        </Field>
                        <Field Type="11" Type_Name="Datablock List">
                          <Name>parameters</Name>
                          <FieldID>3</FieldID>
                          <DBList>
                            <DBList_Instance Name="name">
                              <Field Type="3" Type_Name="String">
                                <Name>name</Name>
                                <FieldID>1</FieldID>
                                <Value>name</Value>
                              </Field>
                              <Field Type="9" Type_Name="Integer Choice">
                                <Name>source</Name>
                                <FieldID>2</FieldID>
                                <Value>100000001</Value>
                              </Field>
                              <Field Type="3" Type_Name="String">
                                <Name>value</Name>
                                <FieldID>3</FieldID>
                                <Value>MyOwnVariable</Value>
                              </Field>
                            </DBList_Instance>
                            <DBList_Instance Name="type">
                              <Field Type="3" Type_Name="String">
                                <Name>name</Name>
                                <FieldID>1</FieldID>
                                <Value>type</Value>
                              </Field>
                              <Field Type="9" Type_Name="Integer Choice">
                                <Name>source</Name>
                                <FieldID>2</FieldID>
                                <Value>100000001</Value>
                              </Field>
                              <Field Type="3" Type_Name="String">
                                <Name>value</Name>
                                <FieldID>3</FieldID>
                                <Value>type_bool</Value>
                              </Field>
                            </DBList_Instance>
                            <DBList_Instance Name="units">
                              <Field Type="3" Type_Name="String">
                                <Name>name</Name>
                                <FieldID>1</FieldID>
