=== SyedTabishAzam/GUIPlugin/sm_db/Database.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Database (Timestamp,Profile*) >
<!ATTLIST Database Name CDATA #REQUIRED>
<!ATTLIST Database Stage_Version CDATA #REQUIRED>
<!ELEMENT Timestamp (#PCDATA)>
<!ELEMENT Profile (#PCDATA)>

=== SyedTabishAzam/GUIPlugin/sm_db/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Database SYSTEM "Database.dtd">
<Database Name="default" Stage_Version="16.0.0">
  <Timestamp>1535347389</Timestamp>
  <Profile>default/art_part.xml</Profile>
  <Profile>default/atmos.xml</Profile>
  <Profile>default/countermeasure.xml</Profile>
  <Profile>default/designator.xml</Profile>
  <Profile>default/detailed_building_prof.xml</Profile>
  <Profile>default/formation.xml</Profile>
  <Profile>default/iff.xml</Profile>
  <Profile>default/me_mission.xml</Profile>
  <Profile>default/me_submission.xml</Profile>
  <Profile>default/ocean.xml</Profile>
  <Profile>default/platform.xml</Profile>
  <Profile>default/radio.xml</Profile>
  <Profile>default/sensor.xml</Profile>
  <Profile>default/special_zone.xml</Profile>
  <Profile>default/supply.xml</Profile>
  <Profile>default/weapon.xml</Profile>
</Database>

=== SyedTabishAzam/GUIPlugin/batch.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Database SYSTEM "Database.dtd">
<Database Name="batch" Stage_Version="16.0.0">
  <Timestamp>1481830601</Timestamp>
  <Profile>batch/art_part.xml</Profile>
  <Profile>batch/atmos.xml</Profile>
  <Profile>batch/countermeasure.xml</Profile>
  <Profile>batch/designator.xml</Profile>
  <Profile>batch/detailed_building_prof.xml</Profile>
  <Profile>batch/formation.xml</Profile>
  <Profile>batch/iff.xml</Profile>
  <Profile>batch/me_mission.xml</Profile>
  <Profile>batch/me_submission.xml</Profile>
  <Profile>batch/ocean.xml</Profile>
  <Profile>batch/platform.xml</Profile>
  <Profile>batch/radio.xml</Profile>
  <Profile>batch/sensor.xml</Profile>
  <Profile>batch/special_zone.xml</Profile>
  <Profile>batch/supply.xml</Profile>
  <Profile>batch/weapon.xml</Profile>
</Database>
